### ISSUE TITLE
syncfile naming odd, both times same

### ISSUE THREAD

**Issue by crotwell** [iris-edu/miniseed2dmc#3]
I think there is a problem with the procstart time in miniseed2dmc.c, at least as far as naming the output sync file. Both times seems to be the same. For example:

-rw-rw-r-- 1 scsn scsn 123042 May 15 16:08 2019-05-15T16:08:37--2019-05-15T16:08:37.sync

Pretty sure this run took several minutes. Start and end times are the same and the end match the file modification time, at least to the minute. Had a quick look at the code, but I don't see where the issue is, other than it seems likely that the starttime is the one wrong.

**Comment by chad-earthscope** [comment]
Thanks.  Fixed in d07bda8b1bbfdd9b7787a1845ccd25b83d7307ae, will be in next release.
